### ISSUE TITLE
Setting tempo?

### ISSUE THREAD

**Issue by petepm** [vishnubob/python-midi#103]
This is more of a question, but I'm looking to create a variable tempo click track. Is there a quick way to set the tempo of a track at certain times? In my case, I have an array of evenly spaced (in real time, not beats) tempo values. Thanks in advance for any help with this!

**Comment by vishnubob** [comment]
https://github.com/vishnubob/python-midi/blob/master/src/events.py#L304

**Comment by stefansullivan** [comment]
When you change the tempo of MIDI file you would need to modify the ticks of all the following ticks. Is there any convenience method for doing this, or do we have to do our own bookkeeping when changing tempo?
