### ISSUE TITLE
Tracks do NOT contain NoteOffEvent after read_midifile("my.mid")?

### ISSUE THREAD

**Issue by star013** [vishnubob/python-midi#104]
Hello!

I try to use python-midi to read a midi file, and parse the note events in it. However, I have trouble distinguishing when a note ends. Some of the note events are listed here:
`midi.TrackNameEvent(tick=0, text='Piano right', data=[80, 105, 97, 110, 111, 32, 114, 105, 103, 104, 116])
midi.ProgramChangeEvent(tick=0, channel=0, data=[0])
midi.ControlChangeEvent(tick=0, channel=0, data=[7, 100])
midi.ControlChangeEvent(tick=0, channel=0, data=[10, 64])
midi.NoteOnEvent(tick=0, channel=0, data=[69, 60])
midi.NoteOnEvent(tick=0, channel=0, data=[74, 73])
midi.TextMetaEvent(tick=0, text='bdca426d104a26ac9dcb070447587523', data=[98, 100, 99, 97, 52, 50, 54, 100, 49, 48, 52, 97, 50, 54, 97, 99, 57, 100, 99, 98, 48, 55, 48, 52, 52, 55, 53, 56, 55, 53, 50, 51])
midi.ControlChangeEvent(tick=0, channel=0, data=[91, 127])
midi.NoteOnEvent(tick=0, channel=0, data=[66, 60])
midi.NoteOnEvent(tick=480, channel=0, data=[66, 0])
midi.NoteOnEvent(tick=0, channel=0, data=[74, 0])
midi.NoteOnEvent(tick=0, channel=0, data=[69, 0])
midi.NoteOnEvent(tick=480, channel=0, data=[79, 66])
midi.NoteOnEvent(tick=120, channel=0, data=[78, 55])
midi.NoteOnEvent(tick=12, channel=0, data=[79, 0])
midi.NoteOnEvent(tick=108, channel=0, data=[76, 54])
midi.NoteOnEvent(tick=12, channel=0, data=[78, 0])
midi.NoteOnEvent(tick=108, channel=0, data=[78, 54])
midi.NoteOnEvent(tick=12, channel=0, data=[76, 0])
`

You see, there is no NoteOffEvent. It is quite strange. The midi files are obtained from [http://www.piano-midi.de/zip/mozart.zip](http://www.piano-midi.de/zip/mozart.zip) and they can be played on my laptop accurately. I guess there must be something wrong in the read midi module. Could you help me?

Thanks.

>

**Comment by semininja** [comment]
This is a common mistake which has been mentioned in other questions. If you look at each event, you'll find that for each note, there's an event with a nonzero velocity and a note with a velocity of zero. The zero-velocity notes are equivalent to NoteOffEvents.

**Comment by star013** [comment]
Thanks for your quick response, @semininja . I have another question. Where could I find the attribute "velocity"? You see that in NoteOnEvent, there are "tick", "channel", and "data", without "velocity"

**Comment by star013** [comment]
I see, thank you @semininja

**Comment by semininja** [comment]
You should use the NoteEvent.get_velocity() method. You can inspect it by looking at the second value in each NoteEvent.data attribute.
