### ISSUE TITLE
How to get every note at the exact moment?

### ISSUE THREAD

**Issue by josefrvaldes** [vishnubob/python-midi#113]
I am working on a project and I'd like to get in the exact moment the active notes from a midi file.

What I'm currently doing is this:
I get the pattern from the midi file.
I can get the active notes from a specific tick (for example, at tick 0, I have C3, E3 and F3 active).

But what I can't do is to loop through all the events with the right tempo.

I see that I have several SetTempoEvents, this one, for example 

`midi.SetTempoEvent(tick=0, data=[7, 161, 32]),`

But I don't know what each parameter means..

And how do I know the exact amount of time that equals a tick?

I know that is already explained in the readme but I still don't understand.. :(

I'm currently doing a while loop and sleeping during some miliseconds and it works more or less.. but I want to make it right.

**Comment by semininja** [comment]
Take a look at Issue #74 for some info about tempo events, and generally, read the previous open and closed issues for more info before opening a new issue.

**Comment by josefrvaldes** [comment]
Yes, you're absolutely right, thanks a lot. 
In fact I had already seen that post but I still didn't get it. But now I've been studying it and I think now I get it. 

Now I understand how to get tempo from a SetTempoEvent and I think I know how to get tick time from bpm and resolution parameters.

Anyway I have another question:

Do you think thats the best way to get what I'm trying to get?

I'm doing something like this (in pseudocode)

    _current_tick = 0
    while _current_tick <= _track_length
        analize_events(_current_tick)
        _current_tick += 1
        time.sleep(_tick_time)

Do you think I have to increment `_current_tick`by 1 each iteration or can that be improved?

Again, thanks a lot!

**Comment by semininja** [comment]
Take a look at my project organ-control for some ideas about playback.

**Comment by josefrvaldes** [comment]
I finally did my project using java, so I will close this issue. Thanks for your help! :)
