### ISSUE TITLE
ImportError: No module named 'containers', Python 3.5.3

### ISSUE THREAD

**Issue by aslyansky-m** [vishnubob/python-midi#119]
Hi!

I'm trying to run
`import midi`
in Python 3.5.3, Anaconda 4.4.0 (64-bit) , Windows 10
but getting an error:

> "...\AppData\Local\conda\conda\envs\py35\python.exe" ".../Documents/py35_tests/audio/test3.py"
Traceback (most recent call last):
  File ".../Documents/py35_tests/audio/test3.py", line 1, in <module>
    import midi
  File "...\AppData\Local\conda\conda\envs\py35\lib\site-packages\midi-0.2.3-py3.5.egg\midi\__init__.py", line 1, in <module>
ImportError: No module named 'containers

Process finished with exit code 1`

Could you help me, please?
Thanks!

**Comment by aslyansky-m** [comment]
Ok, so I fixed it by uninstalling the package and then using:
`pip install git+https://github.com/vishnubob/python-midi@feature/python3`
Thanks!

**Comment by chn-lee-yumi** [comment]
Thanks. I had a similar problem like yours, and I fixed it with your command.

**Comment by TonyElvidge** [comment]
I'm trying to install python-midi on a Raspberry Pi running Python 3.4.2 and get the following

x-x-x-x-x-x

pi@raspberrypi:~ $ pip install git+https://github.com/vishnubob/python-midi@feature/python3
Downloading/unpacking git+https://github.com/vishnubob/python-midi@feature/python3
  Cloning https://github.com/vishnubob/python-midi (to feature/python3) to /tmp/pip-xyxo4C-build
fatal: unable to access 'https://github.com/vishnubob/python-midi/': Could not resolve host: github.com
  Complete output from command /usr/bin/git clone -q https://github.com/vishnubob/python-midi /tmp/pip-xyxo4C-build:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git clone -q https://github.com/vishnubob/python-midi /tmp/pip-xyxo4C-build failed with error code 128 in None
Storing debug log for failure in /home/pi/.pip/pip.log

x-x-x-x-x

Can someone help as I have a project where I want to user the software.

Many thanks
Tony

**Comment by TonyElvidge** [comment]
Hi,
Downloaded the latest Raspian and tried to load pyrhon-midi. I got a little further but still got errors.

x-x-x-x-x-x-x

pi@raspberrypi:~ $ pip install git+https://github.com/vishnubob/python-midi@feature/python3
Collecting git+https://github.com/vishnubob/python-midi@feature/python3
  Cloning https://github.com/vishnubob/python-midi (to feature/python3) to /tmp/pip-buMuEv-build
Installing collected packages: midi
  Running setup.py install for midi ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-buMuEv-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dhR06g-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /usr/lib/python2.7/dist-packages/setuptools/dist.py:333: UserWarning: Normalizing 'v0.2.3' to '0.2.3'
      normalized_version,
    running install
    running build
    running build_py
    file src/sequencer_alsa/sequencer_alsa.py (for module midi.sequencer.sequencer_alsa) not found
    creating build
    creating build/lib.linux-armv6l-2.7
    creating build/lib.linux-armv6l-2.7/midi
    copying src/__init__.py -> build/lib.linux-armv6l-2.7/midi
    copying src/containers.py -> build/lib.linux-armv6l-2.7/midi
    copying src/events.py -> build/lib.linux-armv6l-2.7/midi
    copying src/util.py -> build/lib.linux-armv6l-2.7/midi
    copying src/fileio.py -> build/lib.linux-armv6l-2.7/midi
    copying src/constants.py -> build/lib.linux-armv6l-2.7/midi
    creating build/lib.linux-armv6l-2.7/midi/sequencer
    copying src/sequencer_alsa/__init__.py -> build/lib.linux-armv6l-2.7/midi/sequencer
    copying src/sequencer_alsa/sequencer.py -> build/lib.linux-armv6l-2.7/midi/sequencer
    file src/sequencer_alsa/sequencer_alsa.py (for module midi.sequencer.sequencer_alsa) not found
    running build_ext
    building '_sequencer_alsa' extension
    swigging src/sequencer_alsa/sequencer_alsa.i to src/sequencer_alsa/sequencer_alsa_wrap.c
    swig -python -o src/sequencer_alsa/sequencer_alsa_wrap.c src/sequencer_alsa/sequencer_alsa.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-buMuEv-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dhR06g-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-buMuEv-build/

x-x-x-x-x-x

Any suggestions, so I can start using the software.

Regards
Tony

**Comment by jasondesante** [comment]
same issue for me.  no clue what is wrong... :(

**Comment by FunkyMonkey22** [comment]
Thanks for the answer @chn-lee-yumi

**Comment by PWhiddy** [comment]
@TonyElvidge 
To resolve that last error you need to install swig
`sudo apt-get install swig`

**Comment by JucyCherry** [comment]
i encountered the problem as yours, 
the website you have noted :https://github.com/vishnubob/python-midi@feature/python3
is not existed now, 
i'd appreciated if U help with the right acsess of this lib(python-midi)~~(●'◡'●)ﾉ♥ 
Please forgive my poor English（ฅ´ω`ฅ）

**Comment by ouchengogo** [comment]
the first need to use the  "pip uninstall midi" command!  
Thanks!@chn-lee-yumi

**Comment by Liujingxiu23** [comment]
what can I do to slove the problem when my linux server can not link to the internet?
