### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Pattern'.

### ISSUE THREAD

**Issue by jrmyyy** [vishnubob/python-midi#134]
Hello,

I installed the midi package with this command:  sudo python setup.py install. 
I created a python file to run the example in the presentation of the projet ("Building a MIDI File from scratch"). I just copied and pasted it. However when  I execute the file,  there is an error: 
pattern = midi.Pattern()
AttributeError: 'module' object has no attribute 'Pattern'. 

Thank you in advance for your help.

**Comment by ucasiggcas** [comment]
I got the same problem
