### ISSUE TITLE
How to add notes that start at the same time (e.g. play chords)?

### ISSUE THREAD

**Issue by davetremblay** [vishnubob/python-midi#161]
Hi, it's not well explained how to achieve this. How can I add notes so that they play at the same time, and not one after the other, as it happens when writing and appending the NoteOn and NoteOff events to the track.

**Comment by davetremblay** [comment]
Is this possible with the software? More specifically, I'd need a way to do it with a `for` loop, such as for every "event" in a list, one note is added to the chord that is to be played.

**Comment by semininja** [comment]
It's possible to play chords using individual NoteOn events. All you have to do is make sure that all of the events occur at the same time. If you're using absolute tick counts, use the same tick count for all notes in a chord. If you're using relative tick counts, give each note in a chord *except for the first one* a tick count of zero.
