### ISSUE TITLE
Can't install the package in anaconda

### ISSUE THREAD

**Issue by mattiasu96** [vishnubob/python-midi#182]
I'm trying to install the package inside an Anaconda envirorment using pip (it works fine, i've already used it for many packages) with the command `pip install python-midi`.

Unfortunately i keep getting the following error: 
`ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Mattia\anaconda3\envs\trapgenerator\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mattia\\AppData\\Local\\Temp\\pip-install-3jtz232d\\python-midi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mattia\\AppData\\Local\\Temp\\pip-install-3jtz232d\\python-midi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Mattia\AppData\Local\Temp\pip-install-3jtz232d\python-midi\pip-egg-info'
         cwd: C:\Users\Mattia\AppData\Local\Temp\pip-install-3jtz232d\python-midi\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Mattia\AppData\Local\Temp\pip-install-3jtz232d\python-midi\setup.py", line 42
        print "No sequencer available for '%s' platform." % platform
                                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No sequencer available for '%s' platform." % platform)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

And i can't figure out what is the problem. Anyone has any suggestions?

**Comment by ttuanho** [comment]
I have the same issue

```
pip install python-midi
Collecting python-midi
  Using cached python-midi-v0.2.4.tar.gz (6.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-install-b2dkq9tt/python-midi/setup.py'"'"'; __file__='"'"'/private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-install-b2dkq9tt/python-midi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-pip-egg-info-8yr4ec4i
         cwd: /private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-install-b2dkq9tt/python-midi/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-install-b2dkq9tt/python-midi/setup.py", line 42
        print "No sequencer available for '%s' platform." % platform
                                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No sequencer available for '%s' platform." % platform)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Looks like python-midi is not compatible with python3. I tried this

```
python2.7 -m pip install python-midi
```

and it works!

**Comment by mattiasu96** [comment]
Yes, I found out that the library is not python 3 compatible. 
Anyway there's a compatible version for python 3 here: https://github.com/jameswenzel/mydy

**Comment by ttuanho** [comment]
> Yes, I found out that the library is not python 3 compatible.
> Anyway there's a compatible version for python 3 here: https://github.com/jameswenzel/mydy

Thanks for this.

**Comment by asigalov61** [comment]
> I have the same issue
> 
> ```
> pip install python-midi
> Collecting python-midi
>   Using cached python-midi-v0.2.4.tar.gz (6.1 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /Users/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-install-b2dkq9tt/python-midi/setup.py'"'"'; __file__='"'"'/private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-install-b2dkq9tt/python-midi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-pip-egg-info-8yr4ec4i
>          cwd: /private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-install-b2dkq9tt/python-midi/
>     Complete output (6 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/62/bcw_51452lx3d1fxd_hsq6ch0000gn/T/pip-install-b2dkq9tt/python-midi/setup.py", line 42
>         print "No sequencer available for '%s' platform." % platform
>                                                         ^
>     SyntaxError: Missing parentheses in call to 'print'. Did you mean print("No sequencer available for '%s' platform." % platform)?
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ```
> 
> Looks like python-midi is not compatible with python3. I tried this
> 
> ```
> python2.7 -m pip install python-midi
> ```
> 
> and it works!

Thanks so much. It works.
