### ISSUE TITLE
Octave is incorrect for constants

### ISSUE THREAD

**Issue by DanNixon** [vishnubob/python-midi#51]
If you run the following you would expect to get a result of 60 (that being the correct MIDI value for C4), however it actually returns the value for C3.

```
>>> import midi
>>> midi.C_4
48
```

This seems to be a fault with how the globals are generated in ```constants.py``` that causes every note name constant to be shifted down one octave.

**Comment by vishnubob** [comment]
MIDI specifies frequency to note values, but it does not specify octave numbering.  To quote [Wikipedia](http://en.wikipedia.org/wiki/Scientific_pitch_notation#Similar_systems): "MIDI software and hardware often uses C5 or C3 to represent middle C (note 60)."  Try googling [MIDI octave numbering](https://www.google.com/?gws_rd=ssl#q=midi+octave+number) if you are not convinced.

**Comment by DanNixon** [comment]
The MIDI spec states that 60 should be middle C, which most people will know as the C at 261 Hz.
This and the fact every MIDI device I have used have always used 60 for C4 just made me assume that this was part of the standard.
Looking at some of the other lookup tables I see there are quite a few different mappings from value to note.
