### ISSUE TITLE
Question: how to show the current beat in realtime

### ISSUE THREAD

**Issue by tleyden** [vishnubob/python-midi#65]
I want to create something which can show the current beat while a song is playing back.  It doesn't have to play back the actual song, but it needs to be synchronized with the song playback.  For example, if I start the program and the song at the same time, the program would show the current beat in the song playing back.

It seems like it could be done with the sequencer, although some guidance / examples would be helpful.  Looks like according to the README, there's only an ALSA sequencer working, but I did see some code for an OSX sequencer -- is that known to work?

Also, does it seem feasible without a sequencer so I could avoid messing around with drivers?

**Comment by vishnubob** [comment]
OSX sequencer does not work, currently only ALSA on Linux is supported.  The algorithm would be to scan for all the tempo changes, calculate their wall clock offsets and use something like python's built in schedule module to time everything out.

**Comment by tleyden** [comment]
Thanks
