### ISSUE TITLE
Installation problems with pip

### ISSUE THREAD

**Issue by chaosmail** [vishnubob/python-midi#66]
Hi,

it seems that there are some problems when I try to install the `midi` package via pip.

He is the output
```bash
$ pip install midi
Collecting midi
  Could not find a version that satisfies the requirement midi (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external midi to allow).
No matching distribution found for midi
```
Interesting, that doing a `pip search midi` lists the package.

When I clone the repo and run `pip install -e .` from inside the directory, the installation finishes. However, when I install it like this I cannot import midi (also the script/ commands fail because of the same reason)

```bash
$ python
>>> import midi
ImportError: No module named midi
```

or the script

```bash
$ mididump.py data/confuta.mid 
Traceback (most recent call last):
  File "/usr/local/bin/mididump.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ckoerner/software/python-midi/scripts/mididump.py", line 5, in <module>
    import midi
ImportError: No module named midi
```

When I install the package with the recommended way `python setup.py install` everything works fine. However, I would really like to put the package into the requirements.txt file and install it with pip.

Best,
Christoph

**Comment by vishnubob** [comment]
The pip python package is actually named ```python-midi```:

```
$ pip install python-midi
Collecting python-midi
  Downloading python-midi-v0.2.4.tar.gz
Building wheels for collected packages: python-midi
  Running setup.py bdist_wheel for python-midi
  Stored in directory: /Users/ghall/Library/Caches/pip/wheels/0a/db/7e/cafd42da7ba87eab1b21c5268d0520af9a5fb270f9ca64c1bd
Successfully built python-midi
Installing collected packages: python-midi
Successfully installed python-midi-0.2.4
```

**Comment by chaosmail** [comment]
Thanks for the quick reply!

**Comment by fredpws** [comment]
I am new to python and want to do something with midi files. I would like to install the midi module but will get 

"E: \ Users \ Fred \ AppData \ Local \ Temp \ easy_install-x_rh3hob \ python-midi v0.2.4 \ setup", line 42
Print "No sequencer available for '% s' platform
Syntax Error: Missing parentheses in call to 'print'
Its for the moment very confusing for me
I’am a PHP programmer and now  I’m learning Python
Can you help me please
I’m not so good in English writing but a understand a lot
Greetings

Fred

**Comment by g0ro** [comment]
exec this to install the package for python3 
`pip install git+https://github.com/vishnubob/python-midi@feature/python3`

**Comment by ProcopioPi** [comment]
I tried everything here and didn´t work, I am on windows 10 with python 3.6.3

**Comment by mehrzeller** [comment]
same problem, i think..it is not working under windows (needs alsa libasound2-dev)
anybody any ideas ?
setup.py -->
.......
def configure_platform():
    from sys import platform
    ns = __base__.copy()
    # currently, only the ALSA sequencer is supported
    if platform.startswith('linux'):
        setup_alsa(ns)
        pass
    else:
        print "No sequencer available for '%s' platform." % platform
    return ns
