### ISSUE TITLE
Question: how to set a note to "Minus C2"

### ISSUE THREAD

**Issue by tleyden** [vishnubob/python-midi#67]
Apparently virtual keyboards go down to "minus c2".  How would I specify a note with this pitch in python-midi?

Conversation snippet with the composer I'm working with:

> Minus C2 is the lowest note.  the virtual midi keyboard- not real ones- go all the way down to -C2.   A0 is the low note on a piano, although I think now that is -A1

> C2 is too high- that's one octave below Middle C these days.

> You are starting 4 octaves too high.

**Comment by vishnubob** [comment]
An octave is twelve half steps, so if you need to transpose down 4 octaves, subtract your pitch by (4 * 12).  You can also use the constants, but there is no guarantee they will correctly map (see #51).

**Comment by tleyden** [comment]
Thanks, that helps.  What would the constant be for C-2, or is there no valid constant for anything below A_0?

**Comment by vishnubob** [comment]
Again, see issue #51, along with the code that defines the constants.  In other words, it's better to go by numerical value then octave numbering.

**Comment by tleyden** [comment]
I don't quite understand #51 yet, but I will try to read through all the references and maybe it will make more sense.

**Comment by vishnubob** [comment]
I appreciate that you have a lot of questions, and that understanding often requires reading and then re-reading documentation -- but most of your questions fall squarely within the realm of MIDI, as opposed to python-midi itself.  When opening future issues, I would prefer that you scope your questions appropriately, and utilize other resources to further your understanding.  Thanks.
