### ISSUE TITLE
setup.py not working, missing characters.

### ISSUE THREAD

**Issue by Taitenator** [vishnubob/python-midi#68]
I was trying to install the module, as I plan to do some work with MIDI files and it seemed useful, but I couldn't get setup.py to install. For some reason, in the version I downloaded at least, the brackets around the print statement on line 65 were missing, and so it wouldn't work. When I added them back in, it worked fine.

**Comment by vishnubob** [comment]
Without more information, such as the version you are working with, a backtrace and possibly a pull request, there's not much I can help you with.

**Comment by Taitenator** [comment]
I'd assume it's the latest version, as I only downloaded the zip today. I managed to fix the problem by adding the Brackets as mentioned above, I just thought I'd point it out so you were aware.

**Comment by vishnubob** [comment]
I can not replicate any problem with the current source code.  More over, the current [line 65](https://github.com/vishnubob/python-midi/blob/master/setup.py#L65) has no brackets to speak of.  If there is a bug, I would love to fix it, but I can't without more information.

**Comment by Taitenator** [comment]
The lack of bracket is the problem. When I ran the installation it gave me
an error message telling me it expected there to be brackets due to the
print statement. When I added brackets, it worked, if they aren't there it
doesn't.

**Comment by vishnubob** [comment]
can not replicate due to lack of information, closing issue.
