### ISSUE TITLE
Absolute time position of midi events : how to retrieve resolution?

### ISSUE THREAD

**Issue by jzy3d** [vishnubob/python-midi#69]
You explain well how to compute time position of a midi event based on tick, tempo, and resolution (https://github.com/vishnubob/python-midi#Side_Note_What_is_a_MIDI_Tick).

How can I get the resolution of a loaded midi file? How can I choose a resolution while creating the midi pattern?

Thanks

**Comment by vishnubob** [comment]
The resolution is a member variable of the Pattern class, and is part of its constructor:

https://github.com/vishnubob/python-midi/blob/master/src/containers.py#L6

**Comment by jzy3d** [comment]
Thanks
