### ISSUE TITLE
Note off events of this MIDI file are not parsed

### ISSUE THREAD

**Issue by jzy3d** [vishnubob/python-midi#71]
Only note on events are read from this midi file : http://download.jzy3d.org/debug-deb_passMINp_align.mid

A third party software (Ableton Live) can load the file properly with midi off events. 

<img width="341" alt="capture d ecran 2015-09-21 a 18 07 35" src="https://cloud.githubusercontent.com/assets/2334960/9997302/b2e45e82-608b-11e5-9bbf-c4ad65e166a5.png">

When the MIDI clip is exported from Ableton, it can be properly read by python-midi (see the file as exported by live : http://download.jzy3d.org/debug-poliner-debussy.mid)

To reproduce : 
‘‘‘
p = midi.read_midifile("../data/debug-deb_passMINp_align.mid");
print "tracks : " + repr(len(p))
print p[0]
print p[1][0:20]
‘‘‘

Will output : 

tracks : 2
midi.Track(\
  [midi.TimeSignatureEvent(tick=0, data=[4, 2, 24, 8]),
   midi.SetTempoEvent(tick=0, data=[9, 39, 192]),
   midi.EndOfTrackEvent(tick=0, data=[])])
midi.Track(\
  [midi.NoteOnEvent(tick=0, channel=0, data=[42, 38]),
   midi.NoteOnEvent(tick=22, channel=0, data=[42, 0]),
   midi.NoteOnEvent(tick=38, channel=0, data=[49, 32]),
   midi.NoteOnEvent(tick=22, channel=0, data=[49, 0]),
   midi.NoteOnEvent(tick=38, channel=0, data=[57, 34]),
   midi.NoteOnEvent(tick=22, channel=0, data=[57, 0]),
   midi.NoteOnEvent(tick=38, channel=0, data=[49, 33]),
   midi.NoteOnEvent(tick=22, channel=0, data=[49, 0]),
   midi.NoteOnEvent(tick=38, channel=0, data=[44, 42]),
   midi.NoteOnEvent(tick=22, channel=0, data=[44, 0]),
   midi.NoteOnEvent(tick=38, channel=0, data=[49, 34]),
   midi.NoteOnEvent(tick=22, channel=0, data=[49, 0]),
   midi.NoteOnEvent(tick=38, channel=0, data=[59, 38]),
   midi.NoteOnEvent(tick=22, channel=0, data=[59, 0]),
   midi.NoteOnEvent(tick=38, channel=0, data=[49, 36]),
   midi.NoteOnEvent(tick=22, channel=0, data=[49, 0]),
   midi.NoteOnEvent(tick=38, channel=0, data=[45, 44]),
   midi.NoteOnEvent(tick=22, channel=0, data=[45, 0]),
   midi.NoteOnEvent(tick=38, channel=0, data=[54, 40]),
   midi.NoteOnEvent(tick=22, channel=0, data=[54, 0])])

The MIDI file is taken from the training set of Poliner & Ellis dataset :  http://labrosa.ee.columbia.edu/projects/piano/

**Comment by tdhsmith** [comment]
Many MIDI files will encode note offs as note ons with velocity zero. Velocity is the second data field for note events... every one of your example's "true" note ons is followed by one of these velocity note offs:

```python
midi.NoteOnEvent(tick=0, channel=0, data=[42, 38]), # strike pitch 42 with velocity 38
midi.NoteOnEvent(tick=22, channel=0, data=[42, 0]), # strike pitch 42 with velocity 0 (= no sound)
```

**python-midi** in general won't be implementing any abstract musical concepts that don't exist in the MIDI standard, but PR #59 has some useful code for searching for matching note offs. Read the discussion closely though -- @vishnubob has some important points about how MIDI has no guarantees or expectations about note "state", or the meaning of on and off, and there are a lot of edge cases.

**Comment by jzy3d** [comment]
Many thanks for your suggestions!

**Comment by jzy3d** [comment]
Do you know any existing piece of code handling conversion of midi events to an array of notes with start/stop time?

**Comment by superbock** [comment]
shameless plug:

I used this project as a basis for the MIDI code included in my own audio signal processing library (https://github.com/CPJKU/madmom).

I added conversion from MIDI notes to numpy arrays and vice versa. You can find the code here:
https://github.com/CPJKU/madmom/blob/develop/madmom/utils/midi.py

Please note that I bundled everything in a single file and removed all the stuff I don't need.

HTH
