### ISSUE TITLE
Is there a full document about usage

### ISSUE THREAD

**Issue by aquastar** [vishnubob/python-midi#75]
although example and test are enough to explain its main usage, is there any full documents so that we can get a quick overview?

**Comment by vishnubob** [comment]
there is a [readme](https://github.com/vishnubob/python-midi/blob/master/README.mediawiki).

**Comment by aquastar** [comment]
Thanks. An example is, some codes using python-midi lib could get resolution of variable 'pattern', but I can hardly know such variable by document or even debugging, so I think there should be many vars I don't know

**Comment by vishnubob** [comment]
A lot of python-midi assumes you understand how the MIDI protocol and files work.  My advice is to read up on the technical details of MIDI, and the library will make more sense.  The resolution variable is discussed in the README [here](https://github.com/vishnubob/python-midi#Side_Note_What_is_a_MIDI_Tick).
