### ISSUE TITLE
SetTempoEvent

### ISSUE THREAD

**Issue by Fabioclug** [vishnubob/python-midi#76]
Is there any example of how to use the SetTempoEvent? It seems it takes 2 parameters, but in the Standard MIDI Spec. (http://www.cs.cmu.edu/~music/cmsip/readings/Standard-MIDI-file-format-updated.pdf) the event takes a single parameter, so I didn't understand how to use it properly.

**Comment by vishnubob** [comment]
The `SetTempoEvent` provides a convenience attribute `bpm` that wraps the concrete attribute `mpqn`.  `mpqn`, which stands for microseconds per quarter note, is the value that is actually encoded in the MIDI stream, but this is not the most convenient way to think about tempo.  `bpm`, which stands for beats per minute, automatically converts the internal `mpqn` parameter for your convenience.  In other words, you only need to set one, and the other will automatically reflect that value.

**Comment by Fabioclug** [comment]
Thank you! I was trying to pass the value inside a "data" list, as I've seen in other examples, but passing it through a "bpm" parameter worked.
