### ISSUE TITLE
Is tick information in midi.pattern by read_midifile() correct?

### ISSUE THREAD

**Issue by keunwoochoi** [vishnubob/python-midi#83]
Hi, I'm testing `read_midifile()` with a dummy midi file I created with Logic. The signature set to 4/4 and there are two notes at the second and fourth, i.e. one bar consists of [quater_rest quater_note quater_rest quater_note] in score. However the read_midifile() returns as below:

```
>>> pattern2[0]
midi.Track(\
  [midi.TrackNameEvent(tick=0, text='Inst 2', data=[73, 110, 115, 116, 32, 50]),
   midi.InstrumentNameEvent(tick=0, text='Inst 2', data=[73, 110, 115, 116, 32, 50]),
   midi.TimeSignatureEvent(tick=0, data=[4, 2, 24, 8]),
   midi.KeySignatureEvent(tick=0, data=[0, 0]),
   midi.SmpteOffsetEvent(tick=0, data=[32, 0, 0, 0, 0]),
   midi.SetTempoEvent(tick=0, data=[9, 163, 27]),
   midi.NoteOnEvent(tick=480, channel=0, data=[60, 84]),
   midi.NoteOffEvent(tick=480, channel=0, data=[60, 64]),
   midi.NoteOnEvent(tick=480, channel=0, data=[60, 84]),
   midi.NoteOffEvent(tick=480, channel=0, data=[60, 64]),
   midi.EndOfTrackEvent(tick=0, data=[])])
```

Is it what supposed to return? I also tested with other files, it's consistently returning `480` where I think it should return `960`.

**Comment by semininja** [comment]
How did you come to the expected value of 960? What is the resolution given as?

**Comment by keunwoochoi** [comment]
Isn't it true in any regards - that quarter note == 960 ticks?

**Comment by semininja** [comment]
My understanding is that ticks per beat = resolution, and I have had resolution = 384 before, so I don't think so.

**Comment by keunwoochoi** [comment]
Oh, I see. I think the midi files I'm dealing with have 480 PPQ. I thought the resolution (PPQ) is set to 960  universally. Thanks!
