### ISSUE TITLE
Event.tick value not working correctly

### ISSUE THREAD

**Issue by vaastav** [vishnubob/python-midi#85]
I am not really sure if the tick values that are being added are absolutely correct. For example the tick values I have had are as follows.
The 1st column is the pitch and the 2nd column is the tick value. They are nowhere near or related to the resolution of 480 which they should be.
69 149
69 25
69 162
69 15
69 37
69 10
69 3
69 5
69 33
69 25
69 37
69 20
69 33
69 15
69 37
69 10
69 38
69 5
69 35
69 25
66 156
66 15
68 42
68 10
69 37
69 5
69 36
69 25
69 35
69 20
69 38
69 15
69 30
69 10
69 37
69 5
69 33
69 25
69 30
69 20
69 1
69 15
69 38
69 10
69 31
69 5
69 37
69 25

**Comment by semininja** [comment]
Can you copy the code directly, so we can see some of the full events? Those numbers do seem unlikely for tick counts...

**Comment by semininja** [comment]
Also, are all of those notes supposed to be the same pitch?

**Comment by vaastav** [comment]
def read_midi( filename ):
	pattern = midi.read_midifile( filename )
	notes = []
	note_onsets = {}
	
	for track in pattern:
		note_events = [e for e in track if isinstance(e, midi.NoteEvent)]
		tick = 0
		for e in note_events:
			is_note_on = isinstance(e, midi.NoteOnEvent)
			is_note_off = isinstance(e, midi.NoteOffEvent)
			print(e.pitch,e.tick)
			if is_note_on and e.velocity > 0:
				note_onsets[e.pitch] = e.tick
			
			elif is_note_off or (is_note_on and e.velocity == 0):
				notes.append((e.pitch, normalize(e.tick - note_onsets[e.pitch],pattern.resolution)))
				
			tick = e.tick
	notes = np.asarray(notes)
	return notes

**Comment by vaastav** [comment]
Well that's just a part of the output. This output is from a MIDI file of Beyonce's Halo
I found it weird too that it was producing so many continuous pitches like that

**Comment by semininja** [comment]
A copy of the pattern it self, or at least an excerpt, would be helpful in troubleshooting.

**Comment by vaastav** [comment]
I can probably mail you the file. Its happening with a lot of mid files and I am not sure whats happening. Can I mail a fail to you?

**Comment by vaastav** [comment]
Here is a snippet of the hex data from the mid file
4D 54 68 64 00 00 00 06 00 01 00 0D 01 E0 4D 54 72 6B 00 00 00 25 00 FF 03 04 48 61 6C 6F 00 F0 01 F7 00 FF 58 04 04 02 18 08 00 FF 59 02 03 00 00 FF 51 03 0B 71 B0 00 FF 2F 00 4D 54 72 6B 00 00 01 FF 00 FF 03 03 74 6B 32 00 B1 00 00 00 07 6D 00 0A 40 00 5B 54 00 5D 00 00 20 00 01 C1 2B 83 78 B1 00 00 0F 0B 7F 00 0A 40 0A 4D 20 C6 71 91 26 4D 8E 64 26 00 1B 21 4D 8E 65 21 00 18 23 4C 8E 68 23 00 1D 2A 4C 8E 63 2A 00 17 26 4D 8E 69 26 00 83 73 21 4A 8B 0D 21 00 1B 23 4D 8E 65 23 00 15 2A 4B 8E 6B 2A 00 1D 26 4D 8E 63 26 00 1C 21 49 8E 64 21 00 11 23 4D 8E 6F 23 00 13 2A 49 8E 6D 2A 00 17 26 49 8B 09 26 00 83 77 21 49 8E 69 21 00 20 23 4B 8E 60 23 00 1F 2A 4C 8E 61 2A 00 15 26 4C 8E 6B 26 00 18 21 4D 8E 68 21 00 1E 23 4D 8E 62 23 00 14 2A 4A 8E 6C 2A 00 12 26 4A 8B 0E 26 00 83 75 21 4B 8E 6B 21 00 12 23 4D 8E 6E 23 00 15 2A 4A 8E 6B 2A 00 16 26 49 8E 6A 26 00 21 2D 49 8E 5F 2D 00 1E 2F 4C 8E 62 2F 00 16 2A 49 8E 6A 2A 00 21 26 4B 8A 7F 26 00 83 78 2D 4B 8E 68 2D 00 14 2F 4C 8E 6C 2F 00 15 2A 4B 8E 6B 2A 00 21 26 4D 8E 5F 26 00 12 21 4D 8E 6E 21 00 1A 23 4B 8E 66 23 00 20 2A 4C 8E 60 2A 00 1E 26 4A 8B 02 26 00 83 77 21 4C 8E 69 21 00 12 23 4B 8E 6E 23 00 1B 2A 4B 8E 65 2A 00 12 26 4C 8E 6E 26 00 1C 21 4C 8E 64 21 00 1E 23 4D 8E 62 23 00 13 2A 4C 8E 6D 2A 00 1C 26 4A 8B 04 26 00 83 77 21 49 8E 69 21 00 1B 23 49 8E 65 23 00 14 2A 4C 05 2A 4C 8E 67 2A 00 00 2A 00 17 26 4D 8E 69 26 00 CB 13 23 49 8E 6D 23 00 1F 2A 49 8E 61 2A 00 18 26 4A 8E 68 26 00 15 21 4D 8E 6B 21 00 17 23 4D 8E 69 23 00 11 2A 4D 8E 6F 2A 00 12 26 4A 8B 0E 26 00 84 01 21 4A 8E 5F 21 00 1C 23 4D 8E 64 23 00 1A 2A 4D 8E 66 2A 00 11 26 49 8E 6F 26 00 1A 21 49 8E 66 21 00 12 23 4B 8E 6E 23 00 16 2A 4D 8E 6A 2A 00 21 26 4B 8E 5F 26 00 00 FF

**Comment by semininja** [comment]
Shoot, I can't read MIDI hex...
Try this excerpt, and copy the first 20 or so lines of output:

    import midi
    pattern = midi.readfile([filename])
    print("resolution = {}".format(pattern.resolution))
    print(pattern)

I'll test your code with a file I've got; if the problem is happening with multiple files, it's probably a code problem, but it's possible that there's something weird about the MIDI, and this should help confirm that.

**Comment by vaastav** [comment]
The problem is having with many midi files. But it also works with some midi files too so there is something weird definitely going on.
Here is the output of your code:
resolution = 96
print(pattern[0])
midi.Track(\
  [midi.TrackNameEvent(tick=0, text='Jingle Bells - in Little Bavaria', data=[74, 105, 110, 103, 108, 101, 32, 66, 101, 108, 108, 115, 32, 45, 32, 105, 110, 32, 76, 105, 116, 116, 108, 101, 32, 66, 97, 118, 97, 114, 105, 97]),
   midi.TrackNameEvent(tick=0, text='Christmas Song - Polka Style', data=[67, 104, 114, 105, 115, 116, 109, 97, 115, 32, 83, 111, 110, 103, 32, 45, 32, 80, 111, 108, 107, 97, 32, 83, 116, 121, 108, 101]),
   midi.CopyrightMetaEvent(tick=0, text='Copyright 1997 - Lari/Tan Studios', data=[67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 49, 57, 57, 55, 32, 45, 32, 76, 97, 114, 105, 47, 84, 97, 110, 32, 83, 116, 117, 100, 105, 111, 115]),
   midi.TextMetaEvent(tick=0, text='Sequenced by: Larrie Dee (larrie@pacbell.net)\n', data=[83, 101, 113, 117, 101, 110, 99, 101, 100, 32, 98, 121, 58, 32, 76, 97, 114, 114, 105, 101, 32, 68, 101, 101, 32, 40, 108, 97, 114, 114, 105, 101, 64, 112, 97, 99, 98, 101, 108, 108, 46, 110, 101, 116, 41, 10]),
   midi.TextMetaEvent(tick=0, text='Especially for: Bomi\n', data=[69, 115, 112, 101, 99, 105, 97, 108, 108, 121, 32, 102, 111, 114, 58, 32, 66, 111, 109, 105, 10]),
   midi.TextMetaEvent(tick=0, text='Instructions: Play thru MIDI module, not sound card\n', data=[73, 110, 115, 116, 114, 117, 99, 116, 105, 111, 110, 115, 58, 32, 80, 108, 97, 121, 32, 116, 104, 114, 117, 32, 77, 73, 68, 73, 32, 109, 111, 100, 117, 108, 101, 44, 32, 110, 111, 116, 32, 115, 111, 117, 110, 100, 32, 99, 97, 114, 100, 10]),
   midi.PortEvent(tick=0, data=[0]),
   midi.SysexEvent(tick=0, channel=0, data=[5, 126, 127, 9, 1]),
   midi.PortEvent(tick=0, data=[0]),
   midi.TimeSignatureEvent(tick=0, data=[4, 2, 24, 8]),
   midi.KeySignatureEvent(tick=0, data=[255, 0]),
   midi.SetTempoEvent(tick=0, data=[7, 161, 32]),
   midi.MarkerEvent(tick=0, text='Jingle Bells - in Little Bavaria', data=[74, 105, 110, 103, 108, 101, 32, 66, 101, 108, 108, 115, 32, 45, 32, 105, 110, 32, 76, 105, 116, 116, 108, 101, 32, 66, 97, 118, 97, 114, 105, 97]),
   midi.SetTempoEvent(tick=384, data=[7, 161, 32]),
   midi.EndOfTrackEvent(tick=0, data=[])])
>>> print(pattern[1])
midi.Track(\
  [midi.PortEvent(tick=0, data=[0]),
   midi.TrackNameEvent(tick=0, text='"Jimgle Bells"', data=[34, 74, 105, 109, 103, 108, 101, 32, 66, 101, 108, 108, 115, 34]),
   midi.ControlChangeEvent(tick=96, channel=0, data=[0, 0]),
   midi.ControlChangeEvent(tick=1, channel=0, data=[32, 0]),
   midi.ProgramChangeEvent(tick=1, channel=0, data=[60]),
   midi.ControlChangeEvent(tick=1, channel=0, data=[7, 125]),
   midi.ControlChangeEvent(tick=0, channel=0, data=[10, 64]),
   midi.ControlChangeEvent(tick=285, channel=0, data=[91, 52]),
   midi.ControlChangeEvent(tick=0, channel=0, data=[93, 127]),
   midi.NoteOnEvent(tick=1926, channel=0, data=[60, 114]),
   midi.NoteOnEvent(tick=44, channel=0, data=[69, 110]),

**Comment by tdhsmith** [comment]
Well there you go, you have resolution 96, not 480.

**Comment by vaastav** [comment]
@tdhsmith My code doesnt hardcode resolution either. It reads 96. But even for 96 this is horrible. Plus this is a different file actually. This is a midi file of jingle bells.

**Comment by vaastav** [comment]
Also if there is a way I could contribute to the repo, I would love to

**Comment by tdhsmith** [comment]
Sorry you said 480 at the beginning so it wasn't clear if you had read that value in or not.

Well it could be annotations or lyrics or other non-musical meta-events that are placed at arbitrary timings. If note events follow them in a track it could give them "weird" relative values. Some sheet music software might use ticks "visually" for positioning the view elements stored in meta-events (like lyrics or ornaments).

**Comment by semininja** [comment]
The important parts of the output are the resolution and the NoteOnEvents. Could you copy a chunk of the output from the file you used in the first post? It would be interesting to compare.

**Comment by vaastav** [comment]
print("resolution = {}".format(pattern.resolution))
resolution = 480
>>> print(pattern[0])
midi.Track(\
  [midi.TrackNameEvent(tick=0, text='Halo', data=[72, 97, 108, 111]),
   midi.SysexEvent(tick=0, channel=0, data=[1]),
   midi.TimeSignatureEvent(tick=0, data=[4, 2, 24, 8]),
   midi.KeySignatureEvent(tick=0, data=[3, 0]),
   midi.SetTempoEvent(tick=0, data=[11, 113, 176]),
   midi.EndOfTrackEvent(tick=0, data=[])])
>>> print(pattern[1])
midi.Track(\
  [midi.TrackNameEvent(tick=0, text='tk2', data=[116, 107, 50]),
   midi.ControlChangeEvent(tick=0, channel=1, data=[0, 0]),
   midi.ControlChangeEvent(tick=0, channel=1, data=[7, 109]),
   midi.ControlChangeEvent(tick=0, channel=1, data=[10, 64]),
   midi.ControlChangeEvent(tick=0, channel=1, data=[91, 84]),
   midi.ControlChangeEvent(tick=0, channel=1, data=[93, 0]),
   midi.ControlChangeEvent(tick=0, channel=1, data=[32, 0]),
   midi.ProgramChangeEvent(tick=1, channel=1, data=[43]),
   midi.ControlChangeEvent(tick=504, channel=1, data=[0, 0]),
   midi.ControlChangeEvent(tick=15, channel=1, data=[11, 127]),
   midi.ControlChangeEvent(tick=0, channel=1, data=[10, 64]),
   midi.ControlChangeEvent(tick=10, channel=1, data=[77, 32]),
   midi.NoteOnEvent(tick=9073, channel=1, data=[38, 77]),
   midi.NoteOnEvent(tick=1892, channel=1, data=[38, 0]),
   midi.NoteOnEvent(tick=27, channel=1, data=[33, 77]),
   midi.NoteOnEvent(tick=1893, channel=1, data=[33, 0]),
   midi.NoteOnEvent(tick=24, channel=1, data=[35, 76]),
   midi.NoteOnEvent(tick=1896, channel=1, data=[35, 0]),
   midi.NoteOnEvent(tick=29, channel=1, data=[42, 76]),
   midi.NoteOnEvent(tick=1891, channel=1, data=[42, 0]),
   midi.NoteOnEvent(tick=23, channel=1, data=[38, 77]),
   midi.NoteOnEvent(tick=1897, channel=1, data=[38, 0]),
   midi.NoteOnEvent(tick=499, channel=1, data=[33, 74]),
   midi.NoteOnEvent(tick=1421, channel=1, data=[33, 0]),
   midi.NoteOnEvent(tick=27, channel=1, data=[35, 77]),
   midi.NoteOnEvent(tick=1893, channel=1, data=[35, 0]),
   midi.NoteOnEvent(tick=21, channel=1, data=[42, 75]),
   midi.NoteOnEvent(tick=1899, channel=1, data=[42, 0]),
   midi.NoteOnEvent(tick=29, channel=1, data=[38, 77]),
   midi.NoteOnEvent(tick=1891, channel=1, data=[38, 0]),
   midi.NoteOnEvent(tick=28, channel=1, data=[33, 73]),
   midi.NoteOnEvent(tick=1892, channel=1, data=[33, 0]),
   midi.NoteOnEvent(tick=17, channel=1, data=[35, 77]),
   midi.NoteOnEvent(tick=1903, channel=1, data=[35, 0]),
   midi.NoteOnEvent(tick=19, channel=1, data=[42, 73]),
   midi.NoteOnEvent(tick=1901, channel=1, data=[42, 0]),
   midi.NoteOnEvent(tick=23, channel=1, data=[38, 73]),

**Comment by semininja** [comment]
We can establish from this that the file is not being read correctly somehow. I'm going to boot up my RPi and see if I can replicate the problem.

**Comment by tdhsmith** [comment]
What do you see wrong with this data? All those notes are happening quite close to the beat. It looks like it was just recorded from a human...

**Comment by semininja** [comment]
Compare to the first post; there's clearly something wrong between parsing the file and output from the code that vaastav posted above.

**Comment by tdhsmith** [comment]
Is that supposedly from the beginning though? He's been posting snippets so far.

**Comment by semininja** [comment]
Let's try this: @vaastav Try with [this file](https://github.com/semininja/organ-control/blob/master/BWV555.mid) and post the first 10 lines.

**Comment by vaastav** [comment]
Hi, this is what it outputs with your file
I feel that the frequency makes sense
pattern = midi.read_midifile('BWV555.mid')
>>> print("resolution = {}".format(pattern.resolution))
resolution = 384
>>> print(pattern[0])
midi.Track(\
  [midi.TrackNameEvent(tick=0, text='control track', data=[99, 111, 110, 116, 114, 111, 108, 32, 116, 114, 97, 99, 107]),
   midi.TextMetaEvent(tick=0, text='creator: ', data=[99, 114, 101, 97, 116, 111, 114, 58, 32]),
   midi.TextMetaEvent(tick=0, text='GNU LilyPond 2.18.2           ', data=[71, 78, 85, 32, 76, 105, 108, 121, 80, 111, 110, 100, 32, 50, 46, 49, 56, 46, 50, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32]),
   midi.TimeSignatureEvent(tick=0, data=[4, 2, 18, 8]),
   midi.SetTempoEvent(tick=0, data=[15, 66, 64]),
   midi.TimeSignatureEvent(tick=38400, data=[3, 2, 18, 8]),
   midi.SetTempoEvent(tick=0, data=[7, 161, 32]),
   midi.TimeSignatureEvent(tick=80640, data=[3, 1, 18, 8]),
   midi.EndOfTrackEvent(tick=0, data=[])])
>>> print(pattern[1])
midi.Track(\
  [midi.ProgramChangeEvent(tick=0, channel=0, data=[56]),
   midi.ProgramChangeEvent(tick=0, channel=0, data=[56]),
   midi.InstrumentNameEvent(tick=0, text='trumpet', data=[116, 114, 117, 109, 112, 101, 116]),
   midi.ControlChangeEvent(tick=0, channel=0, data=[7, 100]),
   midi.KeySignatureEvent(tick=0, data=[1, 1]),
   midi.NoteOnEvent(tick=384, channel=0, data=[71, 75]),
   midi.NoteOnEvent(tick=336, channel=0, data=[71, 0]),
   midi.NoteOnEvent(tick=48, channel=0, data=[69, 75]),
   midi.NoteOnEvent(tick=504, channel=0, data=[69, 0]),
   midi.NoteOnEvent(tick=72, channel=0, data=[71, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[71, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[67, 75]),
   midi.NoteOnEvent(tick=504, channel=0, data=[67, 0]),
   midi.NoteOnEvent(tick=72, channel=0, data=[67, 75]),
   midi.NoteOnEvent(tick=360, channel=0, data=[67, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[67, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[67, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[66, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[66, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[64, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[64, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[63, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[63, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[59, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[59, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[71, 75]),
   midi.NoteOnEvent(tick=336, channel=0, data=[71, 0]),
   midi.NoteOnEvent(tick=48, channel=0, data=[69, 75]),
   midi.NoteOnEvent(tick=504, channel=0, data=[69, 0]),
   midi.NoteOnEvent(tick=72, channel=0, data=[71, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[71, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[67, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[67, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[69, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[69, 0]),
   midi.NoteOnEvent(tick=24, channel=0, data=[71, 75]),
   midi.NoteOnEvent(tick=672, channel=0, data=[71, 0]),
   midi.NoteOnEvent(tick=96, channel=0, data=[69, 75]),
   midi.NoteOnEvent(tick=336, channel=0, data=[69, 0]),
   midi.NoteOnEvent(tick=48, channel=0, data=[71, 75]),
   midi.NoteOnEvent(tick=504, channel=0, data=[71, 0]),
   midi.NoteOnEvent(tick=72, channel=0, data=[69, 75]),
   midi.NoteOnEvent(tick=168, channel=0, data=[69, 0]),

**Comment by vishnubob** [comment]
In order to determine if there is a problem with the interpretation of tick values, I will need two things from you @vaastav.  First, a copy of the MIDI file in question somewhere that is accessible on the web (dropbox, github, etc).  Second, a clear description of what you are seeing, and why you think there is a problem with the python MIDI library.

**Comment by vaastav** [comment]
1. Here is the jingle bells file http://www.midiworld.com/download/3954
2. I think the tick values are wrong as I think that the midi files must be a multiple of the resolution.
So if the resolution was 96 then valid ticks would be 24,48,192 and so on. But instead thats not what I am getting for the notes.

**Comment by vishnubob** [comment]
I just used two different MIDI software libraries (`midi-perl` and `mftext` from [abcmidi](http://abc.sourceforge.net/abcMIDI/)) to verify that python-midi's interpretation of the tick values are correct.  As @tdhsmith pointed out, these are typical values you would see from non-quantized recordings made by human beings.  Quantizing note events on 16th or 32nd boundaries yields music that sounds rigid to the human ear, which is why the MIDI file format was designed to capture notes with a higher resolution.  The intent is to capture timing variance that is inherent in all human performance.

**Comment by vaastav** [comment]
@vishnubob Thanks for clearing it up! Do you know of any way of quantizing the note-events? If not, would you be interested if I work on it and contribute it as a pull request?
