### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by Anmol-Singh-Jaggi** [vishnubob/python-midi#90]
I just used python-midi in [one my of my projects](https://github.com/Anmol-Singh-Jaggi/Jukebot) and really liked it.  
Unfortunately, it seems that the development has stalled due to maintainers' lack of time.
I would like to contribute to this project in any way I can, particularly in conversion to Python3.

So, where should I begin ?

**Comment by vishnubob** [comment]
There are a few different areas I could use some volunteers.  In broad strokes, we need more documentation, more tests, and adding new sequencer endpoints (for OSX and windows).  For the python 3.x port, I would like to get the test coverage up and make sure it passes all tests for 2.x and 2.x before merging.  If this is something you are interested in, check out the current travis tests along with the coveralls report to see where the gaps are.
