### ISSUE TITLE
SetTempoEvent data representation in bpm?

### ISSUE THREAD

**Issue by i-Dimensional** [vishnubob/python-midi#93]
I'm trying to convert output from read_midifile() to an easier format, in which time is counted in beats.
I can calculate beats from ticks given the formulas in the readme, but to know the actual bpm applicable at a particular place in the music I have to parse the midi.SetTempoEvents.
However I can't wrap my head around what the data list given by these classes represents. I mean the other objects give midi values (0-127) corresponding to notes and velocity values. But these make no sense to me...
How can I get the new bpm set by the event from the output?

**Comment by vishnubob** [comment]
There is a [get_bpm](https://github.com/vishnubob/python-midi/blob/master/src/events.py#L312) property in `SetTempoEvent`.
