### ISSUE TITLE
Writing Sharp and flat tones?

### ISSUE THREAD

**Issue by Abutler101** [vishnubob/python-midi#94]
is it possible and if so how to write a sharp or flat note with this? I have attempted using #'s to represent sharps but it is the reserved character for denoting a comment

**Comment by sbuckleybonanno** [comment]
You can write notes by appending a midi.NoteOnEvent(), and then a midi.NoteOffEvent(). When you instantiate these events, you specify the note using the "pitch" argument. For example, the note G of the 3rd octave is midi.G_3. If you want to say sharps, for example F# of the 4th octave, you would say midi.Fs_4. The "s" stands for sharp. You can't say "f" for flats, but just use the sharp equivalent (for example, use F# for Gb). Using just sharps and naturals, you can make any note, including flats.
