### ISSUE TITLE
How do SysEx events actually work?

### ISSUE THREAD

**Issue by MaurizioB** [vishnubob/python-midi#95]
I'm trying to understand how to write actual SysEx events, but, so far, I wasn't able to.
I tried appending midi.SysexEvent(data=[list of values]) but it doesn't seem to create a valid MIDI file (at least, not for aplaymidi).
I also tried adding/stripping the leading 240 and trailing 247 SysEx values in different combinations, still with no result.
I was thinking about using struct, but, according to the code, that's not the case.

**Comment by MaurizioB** [comment]
Ok, after analyzing the output of a generated mid file with sysex data in it, I finally found out how this works.
The data is composed by the list of sysex data *without* the leading 240 and trailing 247 values, and preceded by the length of bytes *plus* the terminal 247 value.

So, for example, if the complete original message is this:
`0xf0, 0x00, 0x20, 0x29, 0xf7`
the actual content is this:
`0x00, 0x20, 0x29`
the data for the event will be:
`[0x04, 0x00, 0x20, 0x29]`
or, in integer values:
`[4, 0, 32, 41]`

I hope this helps anybody struggling with the same problem.

**Comment by vishnubob** [comment]
so, in other words, you just had to write your data to an array and everything else just worked? :+1:

**Comment by MaurizioB** [comment]
Well, that seemed to work, until I run into a strange bug yesterday.
If I create a track with a normal event (let's say a note on event), a sysex and another "normal" event, I get a file that seems to be corrupted.
This is an example:

    midi.Track(\
      [midi.NoteOnEvent(tick=0, channel=0, data=[22, 64]),
       midi.SysexEvent(tick=0, channel=0, data=[8, 11, 12, 13, 14, 15, 16, 17]),
       midi.NoteOnEvent(tick=0, channel=0, data=[22, 64]),
       midi.EndOfTrackEvent(tick=0, data=[])])

For this track, kMidimon says: "Unexpected byte (16) at 38 at offset 39Unexpected byte ( 0) at 40 at offset 41Unexpected byte ( 0) at 43 at offset 44".
The strange thing is that the same track without the first NoteOn event outputs a valid file.
Can anyone confirm this?
